export const REGISTER_USER = 'REGISTER_USER';
export const LOGIN_USER = 'LOGIN_USER';
export const LOGOUT_USER = 'LOGOUT_USER';
export const LOAD_COLLECTION = 'LOAD_COLLECTION';
export const LOAD_WATCH_DATA = 'LOAD_WATCH_DATA';
export const LOAD_WATCH_PICTURES = 'LOAD_WATCH_PICTURES';
export const LOAD_WATCH_CREATE_FORM_DATA = 'LOAD_WATCH_CREATE_FORM_DATA';
export const LOAD_WATCH_EDIT_FORM_DATA = 'LOAD_WATCH_EDIT_FORM_DATA';
